product/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>',views.addcomment, name='addcomment'),
    #path('addproperty/<int:id>',views.addproperty, name='addproperty')
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('property/', include('property.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('search/', views.product_search, name='product_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),

    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('property/<int:id>/<slug:slug>/', views.property_detail, name='property_detail'),
    #path('property/', views.property, name='property')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name="user_update"),
    path('password/', views.change_password, name="change_password"),
    path('properties/', views.properties, name="properties"),
    path('propertydetail/<int:id>', views.propertydetail, name="propertydetail"),
    path('comments/', views.comments, name="comments"),
    path('deletecomment/<int:id>', views.deletecomment, name="deletecomment"),
    path('propertyedit/<int:id>', views.propertyedit, name="propertyedit"),
    path('propertydelete/<int:id>', views.propertydelete, name="propertydelete"),
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('properties_detail', kwargs={'slug': self.slug})

class Product(models.Model):
        STATUS = (
            ('True', 'Confirmed'),
            ('False', 'Declined'),
        )
        category = models.ForeignKey(Category, on_delete=models.CASCADE)
        title = models.CharField(max_length=150)
        keywords = models.CharField(max_length=255)
        description = models.CharField(max_length=255)
        image = models.ImageField(blank=True, upload_to='images/')
        price = models.FloatField()
        amount = models.IntegerField()
        detail = RichTextUploadingField()
        address = models.CharField(max_length=255)
        room = models.IntegerField(blank=True, )
        year = models.IntegerField(blank=True, )
        sqm = models.IntegerField(blank=True, )
        slug = models.SlugField(null=False, unique=True)
        status = models.CharField(max_length=10, choices=STATUS)
        create_at = models.DateTimeField(auto_now_add=True)
        update_at = models.DateTimeField(auto_now=True)

        def __str__(self):
            return self.title
        def image_tag(self):
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

        def get_absolute_url(self):
            return reverse('product_detail', kwargs={'slug': self.slug})

class Images(models.Model):
        product = models.ForeignKey(Product, on_delete=models.CASCADE)
        title = models.CharField(max_length=50, blank=True)
        image = models.ImageField(blank=True, upload_to='images/')
        def __str__(self):
            return self.title


class Comment(models.Model):
        STATUS = (
            ('New', 'Yeni'),
            ('True', 'Approved'),
            ('False', 'Declined'),
        )
        product=models.ForeignKey(Product, on_delete=models.CASCADE)
        user=models.ForeignKey(User, on_delete=models.CASCADE)
        subject = models.CharField(max_length=50, blank=True)
        comment = models.TextField(max_length=500, blank=True)
        rate= models.IntegerField(blank=True)
        status=models.CharField(max_length=10, choices=STATUS,default='New')
        ip=models.CharField(max_length=20, blank=True)
        create_at = models.DateTimeField(auto_now_add=True)
        update_at = models.DateTimeField(auto_now=True)
        def __str__(self):
            return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']


#class PropertyForm(ModelForm):
    #class Meta:
        #model = Product
        #fields = ['category', 'title','keywords', 'image', 'price', 'amount', 'detail']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=100, label='Email :')
    first_name = forms.CharField(max_length=100, label='First Name :')
    last_name = forms.CharField(max_length=100, label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactFormMessage, ContactFormu, UserProfile, FAQ
from product.models import Product, Category, Images, Comment
from property.models import Properties, PropetyComment, Galeri


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Properties.objects.filter(status='Confirmed').order_by('?')[:4]
    category = Category.objects.all()
    randomproducts = Properties.objects.filter(status='Confirmed').order_by('?')[:6]
    newproperties = Properties.objects.filter(status='Confirmed').order_by('-id')[:3]
    context = {'setting': setting,
               'category': category,
               'page': 'home',
               'sliderdata': sliderdata,
               'randomproducts': randomproducts,
               'newproperties': newproperties
               }
    return render(request, 'index.html', context)

def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()

    context = {'setting': setting, 'category': category, 'page': 'hakkimizda'}
    return render(request, 'hakkimizda.html', context)

def referanslar(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()

    context = {'setting': setting, 'category': category, 'page': 'referanslar'}
    return render(request, 'referanslar.html', context)

def iletisim(request):
    if request.method == 'POST':
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Mesajınız başarı ile gönderilmiştir. Teşekkürler")
            return HttpResponseRedirect('/iletisim')

    setting = Setting.objects.get(pk=1)
    form = ContactFormu
    category = Category.objects.all()
    context = {'setting': setting, 'category': category, 'form': form}
    return render(request, 'iletisim.html', context)



def category_products(request,id,slug):
    sliderdata = Properties.objects.all()[:4]
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    products = Product.objects.filter(category_id=id, status='True')
    propertys = Properties.objects.filter(category_id=id, status='Confirmed')
    context = {'products': products,
               'category': category,
               'sliderdata': sliderdata,
               'categorydata': categorydata,
               'propertys':propertys,
               }
    return render(request, 'products.html', context)




def product_detail(request,id,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id = id, status ='True')
    context = {'category': category,
               'product': product,
               'images': images,
               'comments': comments,
               'setting': setting,
               }
    return render(request, 'product_detail.html', context)


def product_search(request):

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            sliderdata = Properties.objects.all()[:4]
            category = Category.objects.all()
            query = form.cleaned_data['query']
            catid = form.cleaned_data['catid']
            if catid == 0:
                products = Properties.objects.filter(title__icontains=query)
            else:
                products = Properties.objects.filter(title__icontains=query, category_id=catid)
            #return HttpResponse(products)
            context = { 'products': products,
                        'category': category,
                        'sliderdata': sliderdata,
                        }
            return render(request, 'products_search.html', context)
    return HttpResponseRedirect('/')


def product_search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        product = Properties.objects.filter(title__icontains=q)
        results = []
        for rs in product:
            product_json = {}
            product_json = rs.title
            results.append(product_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Kullanıcı adı veya Şifre yanlış!")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {
        'category': category,
        'setting': setting,
                }
    return render(request, 'login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.png"
            data.save()
            return HttpResponseRedirect('/')
    form = SignUpForm()
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {'category': category,
               'form': form,
               'setting': setting,
               }
    return render(request, 'signup.html', context)

#def property(request):
    #category = Category.objects.all()
    #current_user = request.user
    #profile = UserProfile.objects.get(user_id=current_user.id)
    #context = {
        #'category': category,
        #'profile': profile,
    #}
    #return render(request, 'user_property.html', context)


def property_detail(request,id,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    property = Properties.objects.get(pk=id)
    images = Galeri.objects.filter(property_id=id)
    newproperties = Properties.objects.filter(status='Confirmed', category=property.category).order_by('-id')[:3]
    comments = PropetyComment.objects.filter(property_id=id, status='Approved')
    context = {'category': category,
               'property': property,
               'images': images,
               'newproperties': newproperties,
               'comments': comments,
               'setting': setting,
               }
    return render(request, 'property_detail.html', context)


def faq(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    newproperties = Properties.objects.filter(status='Confirmed').order_by('-id')[:3]
    faq = FAQ.objects.all().order_by('ordernumber')
    context = {'category': category,
               'newproperties': newproperties,
               'faq': faq,
               'setting': setting,
               }
    return render(request, 'faq.html', context)

product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from product.models import CommentForm, Comment #PropertyForm, Product


def index(request):
    return HttpResponse("Product Page")

@login_required(login_url='/login')
def addcomment(request, id):

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user=request.user
            data = Comment()
            data.user_id = current_user.id
            data.product_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Thanks for your comment!")
            url =request.META.get('HTTP_REFERER')
            return HttpResponseRedirect(url)
    return HttpResponse("Comment Failed")


#def addproperty(request,id):

    #if request.method == 'POST':
        #form = PropertyForm(request.POST)
        #if form.is_valid():
            #data = Product()
            #data.description = id
            #data.category = form.cleaned_data['category']
            #data.title = form.cleaned_data['title']
            #data.keywords = form.cleaned_data['keywords']
            #data.image = form.cleaned_data['image']
            #data.price = form.cleaned_data['price']
            #data.amount = form.cleaned_data['amount']
            #data.detail = form.cleaned_data['detail']
            #data.save()
            #messages.success(request, "Konut Eklendi!")
            #return HttpResponseRedirect('/user')
    #return HttpResponse("Addproperty Failed")

home/templates/faq.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} Sıkça Sorulan Sorular {% endblock %}
{% block keywords %} SSS/FAQ  {% endblock %}
{% block description %} SSS/FAQ  {% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}"/>
    <script>
        $( function() {
            $( "#accordion" ).accordion();
        } );
    </script>
{% endblock %}

{% block content %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(../../static/images/hero_bg_1.jpg);height:150px;" data-aos="fade" data-stellar-background-ratio="0.7">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-10">
                    <h1 class="mb-2">Sıkça Sorulan Sorular</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12" data-aos="fade-up" data-aos-delay="100">
                    <table class="table">
                        <div id="accordion">
                            {% for rs in faq %}
                                <h3>{{ rs.question }}</h3>
                                <div>
                                    <p class="text-left">{{ rs.answer }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </table>
                </div>
                <!-- <div class="col-md-3"  data-aos="fade-up" data-aos-delay="200">
                <div class="site-section-title">
                  <h2>İşlemler</h2>
                  <hr>
                </div>
                  <ul class="dropdown">
                      <li><a href="/user" class="text-black">User Profile</a></li>
                      <li><a href="" class="text-black">Update Profile</a></li>
                      <li><a href="" class="text-black">Change Password</a></li>
                      <li><a href="" class="text-black">My Property</a></li>
                      <li><a href="" class="text-black">My Comments</a></li>
                      <li><a href="/logout" class="text-black">Logout</a></li>
                  </ul>
              </div> -->
            </div>
        </div>
    </div>
{% endblock %}

home/templates/product_detail.html
{% extends "homebase.html" %}
{% load static %}
{% load l10n %}
{% block title %}  {{ product.title }} {% endblock %}
{% block keywords %} {{ product.keywords }}  {% endblock %}
{% block description %} {{ product.description }}  {% endblock %}

{% block head %} <link rel="shortcut icon" href="{{ setting.icon.url }}"/> {% endblock %}



{% block content %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url({{ product.image.url }});" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-10">
                    <span class="d-inline-block text-white px-3 mb-3 property-offer-type rounded">Property Details of</span>
                    <h1 class="mb-2">{{ product.title }}</h1>
                    <p class="mb-5"><strong class="h2 text-success font-weight-bold">${{ product.price }}</strong></p>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section site-section-sm">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div>
                        <h2>{{ product.description }}</h2>
                        <hr>
                        <div class="slide-one-item home-slider owl-carousel">
                            <div><img src="{{ product.image.url }}" alt="Image" class="img-fluid"></div>
                            {% for rs in images %}
                                <div><img src="{{ rs.image.url }}" alt="Image" class="img-fluid"></div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="bg-white property-body border-bottom border-left border-right">
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <strong class="text-success h1 mb-3">{{ product.price|localize }}TL</strong>
                            </div>
                            <div class="col-md-6">
                                <ul class="property-specs-wrap mb-3 mb-lg-0  float-lg-right">
                                    <li>
                                        <span class="property-specs">Room</span>
                                        <span class="property-specs-number">{{ product.room }} + 1</span>
                                    </li>
                                    <li>
                                      <span class="property-specs">Year</span>
                                      <span class="property-specs-number">{{ product.year }}</span>
                                    </li>
                                    <li>
                                        <span class="property-specs">SQM</span>
                                        <span class="property-specs-number">{{ product.sqm }}</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6 col-lg-4 text-center border-bottom border-top py-3">
                                <span class="d-inline-block text-black mb-0 caption-text">Home Type</span>
                                <strong class="d-block">{{ product.description }}</strong>
                            </div>
                            <div class="col-md-6 col-lg-4 text-center border-bottom border-top py-3">
                                <span class="d-inline-block text-black mb-0 caption-text">Year Built</span>
                                <strong class="d-block">{{ product.year }}</strong>
                            </div>
                            <div class="col-md-6 col-lg-4 text-center border-bottom border-top py-3">
                                <span class="d-inline-block text-black mb-0 caption-text">Address</span>
                                <strong class="d-block">{{ product.address }}</strong>
                            </div>
                        </div>
                        <h2 class="h4 text-black">Konut Detayları</h2>
                        <p>{{ product.detail|safe }}</p>
                        <div class="row no-gutters mt-5">
                            <div class="col-12">
                                <h2 class="h4 text-black mb-3">Gallery</h2>
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3">
                                <a href="{{ product.image.url }}" class="image-popup gal-item"><img src="{{ product.image.url }}" alt="Image" class="img-fluid" style="height: 100px"></a>
                            </div>
                            {% for rs in images %}
                                <div class="col-sm-6 col-md-4 col-lg-3">
                                    <a href="{{ rs.image.url }}" class="image-popup gal-item"><img src="{{ rs.image.url }}" alt="Image" class="img-fluid" style="height: 100px"></a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="bg-white widget border rounded">
                        <h3 class="h4 text-black widget-title mb-3">Kategoriler</h3>
                        {% load mptt_tags %}
                        <ul class="dropdown arrow-top">
                            {% recursetree category %}
                                <li><a href="/category/{{ node.id }}/{{ node.slug }}" class="text-black">{{ node.title }}</a></li>
                                {% if not node.is_leaf_node %}
                                    <ul>
                                        {{ children }}
                                    </ul>
                                {% endif %}
                            {% endrecursetree %}
                        </ul>
                        </li>
                    </div>
                    <div class="bg-white widget border rounded">
                        <h3 class="h4 text-black widget-title mb-3">Comments</h3>
                        {% for rs in comments %}
                            <div class="border-bottom border-top py-3" >
                                <h3 class="h4 text-black widget-title mb-3">{{ rs.user.username}}</h3>
                                <h6>{{ rs.create_at }}</h6>
                                <hr>
                                <p>{{ rs.comment }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="bg-white widget border rounded">
                        <h3 class="h4 text-black widget-title mb-3">Review</h3>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form action="/product/addcomment/{{ product.id }}" class="form-contact-agent" method="post">
                            {% csrf_token %}
                            <!-- <div class="form-group">
                              <label for="name">Name</label>
                              <input type="text" id="name" class="form-control">
                            </div> -->
                            <div class="form-group">
                                <label for="name">Subject</label>
                                <input type="text" name="subject"  class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="comment">Comment</label>
                                <input type="text" name="comment" id="id_comment" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="name">Rate</label>
                                <div class="icon-star">
                                    <input type="radio" id="star1" name="rate" value="1" /><label for="star1"></label>
                                    <input type="radio" id="star2" name="rate" value="2" /><label for="star2"></label>
                                    <input type="radio" id="star3" name="rate" value="3" /><label for="star3"></label>
                                    <input type="radio" id="star4" name="rate" value="4" /><label for="star4"></label>
                                    <input  type="radio" id="star5" name="rate" value="5" /><label for="star5"></label>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" id="phone" class="btn btn-primary" value="Comment">
                            </div>
                            {% if user.id is not None %}
                            {% else %}
                            {% endif%}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="site-section-title mb-5">
                    <h2>Related Properties</h2>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            {% for rs in relatedproducts %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="property-entry h-100">
                        <a href="/product/{{ rs.id }}/{{ rs.slug }}" class="property-thumbnail">
                            <div class="offer-type-wrap">
                                <span class="offer-type bg-success">Rent</span>
                            </div>
                            <img src="{{ rs.image.url }}" alt="Image" class="img-fluid" style="height: 200px" width="350px">
                        </a>
                        <div class="p-4 property-body">
                            <h2 class="property-title"><a href="/product/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></h2>
                            <span class="property-location d-block mb-3"><span class="property-icon icon-room"></span>{{ rs.address }}</span>
                            <strong class="property-price text-primary mb-3 d-block text-success">{{ rs.price }} TL</strong>
                            <ul class="property-specs-wrap mb-3 mb-lg-0">
                                <li>
                                    <span class="property-specs">Room</span>
                                    <span class="property-specs-number">{{ rs.room }} + 1</span>
                                </li>
                                <li>
                                    <span class="property-specs">Year</span>
                                    <span class="property-specs-number">{{ rs.year }}</span>
                                </li>
                                <li>
                                    <span class="property-specs">SQM</span>
                                    <span class="property-specs-number">{{ rs.sqm }}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}