project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('property/', include('property.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('search/', views.product_search, name='product_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),

    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('property/<int:id>/<slug:slug>/', views.property_detail, name='property_detail'),
    #path('property/', views.property, name='property')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name="user_update"),
    path('password/', views.change_password, name="change_password"),
    path('properties/', views.properties, name="properties"),
    path('propertydetail/<int:id>', views.propertydetail, name="propertydetail"),
    path('comments/', views.comments, name="comments"),
    path('deletecomment/<int:id>', views.deletecomment, name="deletecomment"),
    path('propertyedit/<int:id>', views.propertyedit, name="propertyedit"),
    path('propertydelete/<int:id>', views.propertydelete, name="propertydelete"),
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=30)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField()
    contact = RichTextUploadingField()
    references = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder':'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'form-control', 'placeholder': 'Your  Message'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.username
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=250)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS, default='True')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('properties_detail', kwargs={'slug': self.slug})

class Product(models.Model):
        STATUS = (
            ('True', 'Confirmed'),
            ('False', 'Declined'),
        )
        category = models.ForeignKey(Category, on_delete=models.CASCADE)
        title = models.CharField(max_length=150)
        keywords = models.CharField(max_length=255)
        description = models.CharField(max_length=255)
        image = models.ImageField(blank=True, upload_to='images/')
        price = models.FloatField()
        amount = models.IntegerField()
        detail = RichTextUploadingField()
        address = models.CharField(max_length=255)
        room = models.IntegerField(blank=True, )
        year = models.IntegerField(blank=True, )
        sqm = models.IntegerField(blank=True, )
        slug = models.SlugField(null=False, unique=True)
        status = models.CharField(max_length=10, choices=STATUS)
        create_at = models.DateTimeField(auto_now_add=True)
        update_at = models.DateTimeField(auto_now=True)

        def __str__(self):
            return self.title
        def image_tag(self):
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

        def get_absolute_url(self):
            return reverse('product_detail', kwargs={'slug': self.slug})

class Images(models.Model):
        product = models.ForeignKey(Product, on_delete=models.CASCADE)
        title = models.CharField(max_length=50, blank=True)
        image = models.ImageField(blank=True, upload_to='images/')
        def __str__(self):
            return self.title


class Comment(models.Model):
        STATUS = (
            ('New', 'Yeni'),
            ('True', 'Approved'),
            ('False', 'Declined'),
        )
        product=models.ForeignKey(Product, on_delete=models.CASCADE)
        user=models.ForeignKey(User, on_delete=models.CASCADE)
        subject = models.CharField(max_length=50, blank=True)
        comment = models.TextField(max_length=500, blank=True)
        rate= models.IntegerField(blank=True)
        status=models.CharField(max_length=10, choices=STATUS,default='New')
        ip=models.CharField(max_length=20, blank=True)
        create_at = models.DateTimeField(auto_now_add=True)
        update_at = models.DateTimeField(auto_now=True)
        def __str__(self):
            return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']


#class PropertyForm(ModelForm):
    #class Meta:
        #model = Product
        #fields = ['category', 'title','keywords', 'image', 'price', 'amount', 'detail']

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from home.models import UserProfile, Setting
from product.models import Category, Comment
from property.models import Properties, Galeri, PropetyComment, PropertyForm
from user.forms import UserUpdateForm, ProfileUpdateForm, PropertyUpdateForm


def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
        'category': category,
        'profile': profile,
        'setting': setting,
    }
    return render(request, 'user_profile.html', context)

@login_required(login_url='/login')
def user_update(request):
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your Profile has been updated')
            return redirect('/user')
    else:
        category =Category.objects.all()
        setting = Setting.objects.get(pk=1)
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category' : category,
            'user_form' : user_form,
            'profile_form' : profile_form,
            'profile': profile,
            'setting': setting,
        }
        return render(request, 'user_update.html', context)

@login_required(login_url='/login')
def change_password(request):
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your Password successfully Changed')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form=PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form,
            'category': category,
            'profile': profile,
        })

@login_required(login_url='/login')
def properties(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    properties = Properties.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'profile': profile,
        'properties': properties,
        'setting': setting,
    }
    return render(request, 'user_properties.html', context)

@login_required(login_url='/login')
def propertydetail(request, id):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    properties = Properties.objects.get(user_id=current_user.id, id=id)
    propertyitem = Properties.objects.filter(id=id)
    images = Galeri.objects.filter(property_id=id)
    context = {
        'category': category,
        'profile': profile,
        'properties': properties,
        'propertyitem': propertyitem,
        'images': images,
        'setting': setting,
    }
    return render(request, 'user_property_detail.html', context)

@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    comments = Comment.objects.filter(user_id=current_user.id)
    propertycomments = PropetyComment.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'profile': profile,
        'comments': comments,
        'propertycomments': propertycomments,
        'setting': setting,
    }
    return render(request, 'user_comments.html', context)

@login_required(login_url='/login')
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    PropetyComment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Your Comment has been deleted')
    return HttpResponseRedirect('/user/comments')

@login_required(login_url='/login')
def propertyedit(request, id):
    properties = Properties.objects.get(id=id)
    if request.method == 'POST':
        form = PropertyUpdateForm(request.POST, request.FILES,instance=properties)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Property successfully Upated')
            return HttpResponseRedirect('/user/propertydetail/'+str(id))
        else:
            messages.error(request, 'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/propertyedit/'+str(id))
    else:
        form = PropertyUpdateForm(instance=properties)
        category = Category.objects.all()
        setting = Setting.objects.get(pk=1)
        context = {
            'category': category,
            'form': form,
            'properties': properties,
            'setting': setting,
        }
        return render(request, 'user_propertyedit.html', context)

@login_required(login_url='/login')
def propertydelete(request, id):
    current_user = request.user
    Properties.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Property Deleted!')
    return HttpResponseRedirect('/user/properties')

user/templates/user_menu.html
<div class="site-section-title">
    <h2>Menu</h2>
    <hr>
</div>
<ul class="dropdown">
  <li><a href="/user" class="text-black">User Profile</a></li>
  <li><a href="/property" class="text-black">Add Property</a></li>
  <li><a href="/user/properties/" class="text-black">My Properties</a></li>
  <li><a href="/user/comments/" class="text-black">My Comments</a></li>
  <li><a href="/logout" class="text-black">Logout</a></li>
</ul>

user/templates/user_property.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} Profile | {{ user.username }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %} {{ setting.description }}  {% endblock %}

{% block head %} <link rel="shortcut icon" href="{{ setting.icon.url }}"/> {% endblock %}

{% block content %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(../static/images/hero_bg_2.jpg);height:150px;" data-aos="fade" data-stellar-background-ratio="0.7">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-10">
                    <h1 class="mb-2">Rent Your Own Property</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-4"  data-aos="fade-up" data-aos-delay="200">
                    {% include "user_menu.html" %}
                </div>
                <div class="col-md-8" data-aos="fade-up" data-aos-delay="100">
                    <div class="site-section-title">
                        <h2>Rent Your Own Property</h2>
                    </div>
                    <div class="bg-white widget border rounded">
                        <h3 class="h4 text-black widget-title mb-3">Your Property Information</h3>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message|safe }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form action="/property/addproperty/" class="form-contact-agent" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                            {% load mptt_tags %}
                              <label for="category">Category</label>
                            <select id="category" name="category">
                              {% recursetree category %}
                                  {% if node.is_leaf_node %}
                                <option value="{{ node.id }}" id="id_category" class="form-control">{{ node.title }}</option>
                                  {% endif %}
                              {% endrecursetree %}
                            </select>
                            </div>
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" name="title" id="id_title" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="keywords">keywords</label>
                                <input type="text" name="keywords" id="id_keywords" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="Description">Description</label>
                                <input type="text" name="description" id="id_description" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" name="image" id="id_image" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" name="price" id="id_price" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="Address">Address</label>
                                <input type="text" name="address" id="id_address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="Room">Room</label>
                                <input type="text" name="room" id="id_room" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="year">year</label>
                                <input type="text" name="year" id="id_year" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="sqm">Sqm</label>
                                <input type="text" name="sqm" id="id_sqm" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="detail">Detail</label>
                                <textarea name="detail" id="id_detail" class="form-control"></textarea>
                            </div>

                            <div class="form-group">
                                <input type="submit" id="phone" class="btn btn-primary" value="Create advert">
                            </div>
                            {% if user.id is not None %}
                            {% else %}
                            {% endif%}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user_property_detail.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} {{ properties.title }} {% endblock %}
{% block keywords %} {{ properties.keywords }}  {% endblock %}
{% block description %} {{ properties.description }}  {% endblock %}

{% block head %} <link rel="shortcut icon" href="{{ setting.icon.url }}"/> {% endblock %}

{% block content %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url({{ properties.image.url }});height:150px;" data-aos="fade" data-stellar-background-ratio="0.7">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-10">
                    <h1 class="mb-2">{{ properties.title }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-4"  data-aos="fade-up" data-aos-delay="200">
                    {% include "user_menu.html" %}
                </div>
                <div class="col-md-8" data-aos="fade-up" data-aos-delay="100">
                    <div class="site-section-title">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message|safe }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <h2>Property Detail</h2>
                    </div>
                    <table class="table">
                        <tr>
                            <th class="text-left">Name</th>
                            <td class="text-left"><a href="/property/{{ properties.id }}/{{ properties.slug }}">{{ properties.title }}</a></td>
                        </tr>
                        <tr>
                            <th class="text-left">Category</th>
                            <td class="text-left">{{ properties.category }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Description</th>
                            <td class="text-left">{{ properties.description }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Address</th>
                            <td class="text-left">{{ properties.address }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Price</th>
                            <td class="text-left">{{ properties.price }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Room</th>
                            <td class="text-left">{{ properties.room }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Year</th>
                            <td class="text-left">{{ properties.year }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Detail</th>
                            <td class="text-left">{{ properties.detail|safe }}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Status</th>
                            <td class="text-left">{{ properties.status }}</td>
                        </tr>
                        <tr>
                            <th class="text-left"><a href="/user/propertydelete/{{ properties.id }}" class="btn btn-outline-danger rounded-0 py-2 px-5" onclick="return confirm('This Property will be deleted!')">Delete</a></th>
                            <td class="text-left"><a href="/user/propertyedit/{{ properties.id }}" class="btn btn-outline-primary rounded-0 py-2 px-5">Update</a></td>
                        </tr>
                    </table>
                    <br>
                    <hr>
                    <div class="row no-gutters mt-5">
                        <div class="col-12">
                            <h2 class="h4 text-black mb-3">Gallery</h2>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <a href="{{ properties.image.url }}" class="image-popup gal-item"><img src="{{ properties.image.url }}" alt="Image" class="img-fluid" style="height: 125px"></a>
                        </div>
                        {% for rs in images %}
                            <div class="col-sm-6 col-md-4 col-lg-3">
                                <a href="{{ rs.image.url }}" class="image-popup gal-item"><img src="{{ rs.image.url }}" alt="Image" class="img-fluid" style="height: 125px"></a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="site-section-title">
                        <br>
                        <hr>
                        <h2>Add More Images</h2>
                    </div>
                    <form action="/property/addgaleri/{{ properties.id }}" class="form-contact-agent" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- <div class="form-group">
                          <label for="name">Name</label>
                          <input type="text" id="name" class="form-control">
                        </div> -->
                        <div class="form-group">
                            <label for="name">Title</label>
                            <input type="text" name="title"  class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="image">Image</label>
                            <input type="file" name="image" id="id_image" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="submit" id="phone" class="btn btn-primary" value="Upload">
                        </div>
                        {% if user.id is not None %}
                        {% else %}
                        {% endif%}
                    </form>
                </div>
                <!-- <div class="col-md-3"  data-aos="fade-up" data-aos-delay="200">
                <div class="site-section-title">
                  <h2>İşlemler</h2>
                  <hr>
                </div>
                  <ul class="dropdown">
                      <li><a href="/user" class="text-black">User Profile</a></li>
                      <li><a href="" class="text-black">Update Profile</a></li>
                      <li><a href="" class="text-black">Change Password</a></li>
                      <li><a href="" class="text-black">My Property</a></li>
                      <li><a href="" class="text-black">My Comments</a></li>
                      <li><a href="/logout" class="text-black">Logout</a></li>
                  </ul>
              </div> -->
            </div>
        </div>
    </div>

{% endblock %}